### ISSUE TITLE
the auto-enhance gif is too large and also too fast

### ISSUE THREAD

**Issue by yan7109** [Polarrco/PolarrAlbumAndroidSDK#4]
the auto-enhance function needs a better way to view the before and after
right now it's not obvious, ideally they are shown top and bottom with proper labels
also the gif size doesn't match the size of the other gifs, plus it's too fast

**Comment by yan7109** [comment]
Also, it will be good to have zoom in the before and after view so they can see the difference. Or have a way to export the auto-enhanced photo.

**Comment by c01-in** [comment]
9c8c76eed707ac816ecad9eacb6885e4b3f933a2
